module.exports = {
  "ALIVE_IMG": "",
  "FOOT": "© LURDBEE TECH💚",
  "PREFIX": ".",
  "AUTO_READ_STATUS": "true",
  "MODE": "private",
  "BOT_NUMBER": "94742274855",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": "true",
  "AUTO_VOICE": "true",
  "ANTI_BAD": "warn",
  "ANTI_BOT": "true",
  "ANTI_CALL": "true",
  "ANTI_LINK": "true",
  "ANTI_PHOTO": "warn",
  "ANTI_STICKER": "warn",
  "ANTI_DELETE": false,
  "DELETEMSGSENDTO": "94742274855",
  "ALWAYS_ONLINE": "true",
  "MOROCCO_BLOCK": "false",
  "OWNER_NAME": "©𝐌𝐑 𝐌𝐀𝐍𝐔𝐋 𝐎𝐅𝐂 💚",
  "OWNER_NUMBER": "2349165661959",
  "AUTO_BIO": "true",
  "AUTO_TYPING": "true",
  "AUTO_RECORDING": "true",
  "WARN_COUNT": "3",
  "AUTO_STICKER":  "true"
};
